// ============================================================
//  kanji_data.js
//  Add your kanji here. Each entry needs:
//    kanji   — the character(s)
//    reading — hiragana reading
//    meaning — English meaning
//    hint    — memory hook
//    tags    — array: level ("N5","N4","N3") + type ("single","combo")
// ============================================================

const kanjiData = [

  { kanji:"会う", reading:"あう", meaning:"to meet", hint:"Meet someone", tags:["N3","soumatome"] },
  { kanji:"会話", reading:"かいわ", meaning:"conversation", hint:"Talking together", tags:["N3","soumatome"] },
  { kanji:"会社", reading:"かいしゃ", meaning:"company", hint:"Business organization", tags:["N3","soumatome"] },
  { kanji:"社会", reading:"しゃかい", meaning:"society", hint:"Human community", tags:["N3","soumatome"] },
  { kanji:"会議", reading:"かいぎ", meaning:"meeting", hint:"Formal discussion", tags:["N3","soumatome"] },
  { kanji:"会場", reading:"かいじょう", meaning:"venue", hint:"Place of event", tags:["N3","soumatome"] },
  { kanji:"合う", reading:"あう", meaning:"to fit / match", hint:"Be suitable", tags:["N3","soumatome"] },
  { kanji:"合計", reading:"ごうけい", meaning:"total", hint:"Final sum", tags:["N3","soumatome"] },
  { kanji:"場合", reading:"ばあい", meaning:"case / situation", hint:"Specific condition", tags:["N3","soumatome"] },
  { kanji:"間に合う", reading:"まにあう", meaning:"to be in time", hint:"Not be late", tags:["N3","soumatome"] },

  { kanji:"合格", reading:"ごうかく", meaning:"pass exam", hint:"Successful result", tags:["N3","soumatome"] },
  { kanji:"相手", reading:"あいて", meaning:"partner / opponent", hint:"Other person", tags:["N3","soumatome"] },
  { kanji:"相談", reading:"そうだん", meaning:"consultation", hint:"Discussing problems", tags:["N3","soumatome"] },
  { kanji:"相当", reading:"そうとう", meaning:"considerable", hint:"Quite a lot", tags:["N3","soumatome"] },
  { kanji:"愛", reading:"あい", meaning:"love", hint:"Strong affection", tags:["N3","soumatome"] },
  { kanji:"愛情", reading:"あいじょう", meaning:"affection", hint:"Warm feelings", tags:["N3","soumatome"] },
  { kanji:"挨拶", reading:"あいさつ", meaning:"greeting", hint:"Hello/goodbye phrases", tags:["N3","soumatome"] },
  { kanji:"曖昧", reading:"あいまい", meaning:"vague", hint:"Not clear", tags:["N3","soumatome"] },
  { kanji:"握手", reading:"あくしゅ", meaning:"handshake", hint:"Greeting with hands", tags:["N3","soumatome"] },
  { kanji:"扱う", reading:"あつかう", meaning:"to handle", hint:"Deal with something", tags:["N3","soumatome"] },

  { kanji:"安全", reading:"あんぜん", meaning:"safety", hint:"No danger", tags:["N3","soumatome"] },
  { kanji:"安心", reading:"あんしん", meaning:"relief", hint:"Feeling secure", tags:["N3","soumatome"] },
  { kanji:"安定", reading:"あんてい", meaning:"stability", hint:"Steady condition", tags:["N3","soumatome"] },
  { kanji:"案内", reading:"あんない", meaning:"guidance", hint:"Showing directions", tags:["N3","soumatome"] },
  { kanji:"案外", reading:"あんがい", meaning:"unexpectedly", hint:"Contrary to expectation", tags:["N3","soumatome"] },
  { kanji:"以上", reading:"いじょう", meaning:"more than", hint:"Greater than amount", tags:["N3","soumatome"] },
  { kanji:"以下", reading:"いか", meaning:"less than", hint:"Below amount", tags:["N3","soumatome"] },
  { kanji:"以外", reading:"いがい", meaning:"except", hint:"Other than", tags:["N3","soumatome"] },
  { kanji:"意外", reading:"いがい", meaning:"unexpected", hint:"Surprising result", tags:["N3","soumatome"] },
  { kanji:"以前", reading:"いぜん", meaning:"before", hint:"Prior time", tags:["N3","soumatome"] },

  { kanji:"以後", reading:"いご", meaning:"after this", hint:"From now on", tags:["N3","soumatome"] },
  { kanji:"衣服", reading:"いふく", meaning:"clothing", hint:"Things worn", tags:["N3","soumatome"] },
  { kanji:"位置", reading:"いち", meaning:"position", hint:"Location of something", tags:["N3","soumatome"] },
  { kanji:"地位", reading:"ちい", meaning:"status", hint:"Social position", tags:["N3","soumatome"] },
  { kanji:"周囲", reading:"しゅうい", meaning:"surroundings", hint:"Area around", tags:["N3","soumatome"] },
  { kanji:"囲む", reading:"かこむ", meaning:"to surround", hint:"Encircle something", tags:["N3","soumatome"] },
  { kanji:"医者", reading:"いしゃ", meaning:"doctor", hint:"Medical professional", tags:["N3","soumatome"] },
  { kanji:"医学", reading:"いがく", meaning:"medical science", hint:"Study of medicine", tags:["N3","soumatome"] },
  { kanji:"委員", reading:"いいん", meaning:"committee member", hint:"Member of committee", tags:["N3","soumatome"] },
  { kanji:"意味", reading:"いみ", meaning:"meaning", hint:"What something signifies", tags:["N3","soumatome"] },

  { kanji:"意見", reading:"いけん", meaning:"opinion", hint:"Personal idea", tags:["N3","soumatome"] },
  { kanji:"用意", reading:"ようい", meaning:"preparation", hint:"Getting ready", tags:["N3","soumatome"] },
  { kanji:"注意", reading:"ちゅうい", meaning:"caution", hint:"Be careful", tags:["N3","soumatome"] },
  { kanji:"育つ", reading:"そだつ", meaning:"to grow", hint:"Become bigger", tags:["N3","soumatome"] },
  { kanji:"育てる", reading:"そだてる", meaning:"to raise", hint:"Bring up child/plant", tags:["N3","soumatome"] },
  { kanji:"教育", reading:"きょういく", meaning:"education", hint:"Teaching and learning", tags:["N3","soumatome"] },
  { kanji:"会社員", reading:"かいしゃいん", meaning:"company employee", hint:"Office worker", tags:["N3","soumatome"] },
  { kanji:"店員", reading:"てんいん", meaning:"shop clerk", hint:"Store worker", tags:["N3","soumatome"] },
  { kanji:"入院", reading:"にゅういん", meaning:"hospitalization", hint:"Stay in hospital", tags:["N3","soumatome"] },
  { kanji:"退院", reading:"たいいん", meaning:"leave hospital", hint:"Discharge from hospital", tags:["N3","soumatome"] }

  { kanji:"印象", reading:"いんしょう", meaning:"impression", hint:"Feeling received", tags:["N3","soumatome"] },
  { kanji:"印刷", reading:"いんさつ", meaning:"printing", hint:"Putting on paper", tags:["N3","soumatome"] },
  { kanji:"飲食店", reading:"いんしょくてん", meaning:"restaurant", hint:"Food and drink shop", tags:["N3","soumatome"] },
  { kanji:"運転", reading:"うんてん", meaning:"driving", hint:"Operating vehicle", tags:["N3","soumatome"] },
  { kanji:"運動", reading:"うんどう", meaning:"exercise", hint:"Physical activity", tags:["N3","soumatome"] },
  { kanji:"幸運", reading:"こううん", meaning:"good luck", hint:"Fortunate event", tags:["N3","soumatome"] },
  { kanji:"水泳", reading:"すいえい", meaning:"swimming", hint:"Swimming activity", tags:["N3","soumatome"] },
  { kanji:"英語", reading:"えいご", meaning:"English language", hint:"Language of England", tags:["N3","soumatome"] },
  { kanji:"英会話", reading:"えいかいわ", meaning:"English conversation", hint:"Speaking English", tags:["N3","soumatome"] },
  { kanji:"映画", reading:"えいが", meaning:"movie", hint:"Film shown in theater", tags:["N3","soumatome"] },

  { kanji:"上映", reading:"じょうえい", meaning:"movie showing", hint:"Displaying a film", tags:["N3","soumatome"] },
  { kanji:"反映", reading:"はんえい", meaning:"reflection", hint:"Something reflected", tags:["N3","soumatome"] },
  { kanji:"栄養", reading:"えいよう", meaning:"nutrition", hint:"Necessary nutrients", tags:["N3","soumatome"] },
  { kanji:"繁栄", reading:"はんえい", meaning:"prosperity", hint:"Successful flourishing", tags:["N3","soumatome"] },
  { kanji:"営業", reading:"えいぎょう", meaning:"business operation", hint:"Commercial activity", tags:["N3","soumatome"] },
  { kanji:"営業中", reading:"えいぎょうちゅう", meaning:"open for business", hint:"Currently operating", tags:["N3","soumatome"] },
  { kanji:"経営", reading:"けいえい", meaning:"management", hint:"Running company/business", tags:["N3","soumatome"] },
  { kanji:"衛生", reading:"えいせい", meaning:"hygiene", hint:"Cleanliness for health", tags:["N3","soumatome"] },
  { kanji:"人工衛星", reading:"じんこうえいせい", meaning:"artificial satellite", hint:"Object orbiting Earth", tags:["N3","soumatome"] },
  { kanji:"駅員", reading:"えきいん", meaning:"station employee", hint:"Worker at station", tags:["N3","soumatome"] },

  { kanji:"駅前", reading:"えきまえ", meaning:"in front of station", hint:"Area near station", tags:["N3","soumatome"] },
  { kanji:"液体", reading:"えきたい", meaning:"liquid", hint:"Fluid substance", tags:["N3","soumatome"] },
  { kanji:"笑顔", reading:"えがお", meaning:"smiling face", hint:"Happy expression", tags:["N3","soumatome"] },
  { kanji:"遠足", reading:"えんそく", meaning:"school excursion", hint:"Educational trip", tags:["N3","soumatome"] },
  { kanji:"応援", reading:"おうえん", meaning:"support / cheering", hint:"Encouragement", tags:["N3","soumatome"] },
  { kanji:"応募", reading:"おうぼ", meaning:"application", hint:"Apply for something", tags:["N3","soumatome"] },
  { kanji:"応答", reading:"おうとう", meaning:"response", hint:"Replying to something", tags:["N3","soumatome"] },
  { kanji:"往復", reading:"おうふく", meaning:"round trip", hint:"Go and return", tags:["N3","soumatome"] },
  { kanji:"横断歩道", reading:"おうだんほどう", meaning:"crosswalk", hint:"Pedestrian crossing", tags:["N3","soumatome"] },
  { kanji:"王様", reading:"おうさま", meaning:"king", hint:"Male ruler", tags:["N3","soumatome"] },

  { kanji:"屋上", reading:"おくじょう", meaning:"rooftop", hint:"Top of building", tags:["N3","soumatome"] },
  { kanji:"贈り物", reading:"おくりもの", meaning:"gift", hint:"Present given to someone", tags:["N3","soumatome"] },
  { kanji:"行う", reading:"おこなう", meaning:"to perform", hint:"Carry out action", tags:["N3","soumatome"] },
  { kanji:"怒る", reading:"おこる", meaning:"to get angry", hint:"Become mad", tags:["N3","soumatome"] },
  { kanji:"幼い", reading:"おさない", meaning:"young / childish", hint:"Very little child", tags:["N3","soumatome"] },
  { kanji:"収める", reading:"おさめる", meaning:"to obtain", hint:"Get something", tags:["N3","soumatome"] },
  { kanji:"収入", reading:"しゅうにゅう", meaning:"income", hint:"Money received", tags:["N3","soumatome"] },
  { kanji:"収拾", reading:"しゅうしゅう", meaning:"settlement", hint:"Bringing under control", tags:["N3","soumatome"] },
  { kanji:"落ち着く", reading:"おちつく", meaning:"to calm down", hint:"Become relaxed", tags:["N3","soumatome"] },
  { kanji:"落とし物", reading:"おとしもの", meaning:"lost item", hint:"Thing accidentally dropped", tags:["N3","soumatome"] },

  { kanji:"踊る", reading:"おどる", meaning:"to dance", hint:"Move rhythmically", tags:["N3","soumatome"] },
  { kanji:"驚く", reading:"おどろく", meaning:"to be surprised", hint:"Feel shock", tags:["N3","soumatome"] },
  { kanji:"お祭り", reading:"おまつり", meaning:"festival", hint:"Traditional celebration", tags:["N3","soumatome"] },
  { kanji:"親", reading:"おや", meaning:"parent", hint:"Father or mother", tags:["N3","soumatome"] },
  { kanji:"親切", reading:"しんせつ", meaning:"kindness", hint:"Helpful behavior", tags:["N3","soumatome"] },
  { kanji:"泳ぐ", reading:"およぐ", meaning:"to swim", hint:"Move in water", tags:["N3","soumatome"] },
  { kanji:"下りる", reading:"おりる", meaning:"to get off", hint:"Leave train/bus", tags:["N3","soumatome"] },
  { kanji:"折る", reading:"おる", meaning:"to fold / break", hint:"Bend into shape", tags:["N3","soumatome"] },
  { kanji:"終わり", reading:"おわり", meaning:"end", hint:"Conclusion point", tags:["N3","soumatome"] },
  { kanji:"温度", reading:"おんど", meaning:"temperature", hint:"Hotness or coldness", tags:["N3","soumatome"] }

  { kanji:"音", reading:"おと", meaning:"sound", hint:"Something heard", tags:["N3","soumatome"] },
  { kanji:"音楽", reading:"おんがく", meaning:"music", hint:"Musical art", tags:["N3","soumatome"] },
  { kanji:"音声", reading:"おんせい", meaning:"voice / sound", hint:"Audio sound", tags:["N3","soumatome"] },
  { kanji:"温泉", reading:"おんせん", meaning:"hot spring", hint:"Natural hot bath", tags:["N3","soumatome"] },
  { kanji:"温暖", reading:"おんだん", meaning:"warm climate", hint:"Mild temperature", tags:["N3","soumatome"] },
  { kanji:"会計", reading:"かいけい", meaning:"accounting / bill", hint:"Payment calculation", tags:["N3","soumatome"] },
  { kanji:"解決", reading:"かいけつ", meaning:"solution", hint:"Solving problem", tags:["N3","soumatome"] },
  { kanji:"解説", reading:"かいせつ", meaning:"explanation", hint:"Detailed commentary", tags:["N3","soumatome"] },
  { kanji:"改善", reading:"かいぜん", meaning:"improvement", hint:"Making better", tags:["N3","soumatome"] },
  { kanji:"快適", reading:"かいてき", meaning:"comfortable", hint:"Pleasant condition", tags:["N3","soumatome"] },

  { kanji:"回収", reading:"かいしゅう", meaning:"collection", hint:"Gathering things back", tags:["N3","soumatome"] },
  { kanji:"回復", reading:"かいふく", meaning:"recovery", hint:"Returning to normal", tags:["N3","soumatome"] },
  { kanji:"回数", reading:"かいすう", meaning:"number of times", hint:"Frequency count", tags:["N3","soumatome"] },
  { kanji:"絵画", reading:"かいが", meaning:"painting", hint:"Artwork picture", tags:["N3","soumatome"] },
  { kanji:"海外", reading:"かいがい", meaning:"overseas", hint:"Foreign countries", tags:["N3","soumatome"] },
  { kanji:"会話力", reading:"かいわりょく", meaning:"conversation skill", hint:"Speaking ability", tags:["N3","soumatome"] },
  { kanji:"科学", reading:"かがく", meaning:"science", hint:"Scientific study", tags:["N3","soumatome"] },
  { kanji:"化学", reading:"かがく", meaning:"chemistry", hint:"Study of substances", tags:["N3","soumatome"] },
  { kanji:"係員", reading:"かかりいん", meaning:"staff member", hint:"Person in charge", tags:["N3","soumatome"] },
  { kanji:"価格", reading:"かかく", meaning:"price", hint:"Cost of item", tags:["N3","soumatome"] },

  { kanji:"確認", reading:"かくにん", meaning:"confirmation", hint:"Checking carefully", tags:["N3","soumatome"] },
  { kanji:"確実", reading:"かくじつ", meaning:"certain / reliable", hint:"Definitely true", tags:["N3","soumatome"] },
  { kanji:"隠れる", reading:"かくれる", meaning:"to hide", hint:"Become unseen", tags:["N3","soumatome"] },
  { kanji:"学期", reading:"がっき", meaning:"school term", hint:"Part of school year", tags:["N3","soumatome"] },
  { kanji:"楽器", reading:"がっき", meaning:"musical instrument", hint:"Tool for music", tags:["N3","soumatome"] },
  { kanji:"活動", reading:"かつどう", meaning:"activity", hint:"Action or movement", tags:["N3","soumatome"] },
  { kanji:"活用", reading:"かつよう", meaning:"practical use", hint:"Use effectively", tags:["N3","soumatome"] },
  { kanji:"勝つ", reading:"かつ", meaning:"to win", hint:"Be victorious", tags:["N3","soumatome"] },
  { kanji:"価値", reading:"かち", meaning:"value", hint:"Worth of something", tags:["N3","soumatome"] },
  { kanji:"悲しい", reading:"かなしい", meaning:"sad", hint:"Feeling sorrow", tags:["N3","soumatome"] },

  { kanji:"必ず", reading:"かならず", meaning:"certainly", hint:"Without fail", tags:["N3","soumatome"] },
  { kanji:"可能", reading:"かのう", meaning:"possible", hint:"Able to happen", tags:["N3","soumatome"] },
  { kanji:"我慢", reading:"がまん", meaning:"patience", hint:"Enduring hardship", tags:["N3","soumatome"] },
  { kanji:"通う", reading:"かよう", meaning:"to commute", hint:"Go regularly", tags:["N3","soumatome"] },
  { kanji:"彼女", reading:"かのじょ", meaning:"girlfriend / she", hint:"Female person", tags:["N3","soumatome"] },
  { kanji:"考え", reading:"かんがえ", meaning:"thought / idea", hint:"Way of thinking", tags:["N3","soumatome"] },
  { kanji:"考える", reading:"かんがえる", meaning:"to think", hint:"Use mind", tags:["N3","soumatome"] },
  { kanji:"関係", reading:"かんけい", meaning:"relationship", hint:"Connection between things", tags:["N3","soumatome"] },
  { kanji:"感謝", reading:"かんしゃ", meaning:"gratitude", hint:"Feeling thankful", tags:["N3","soumatome"] },
  { kanji:"感情", reading:"かんじょう", meaning:"emotion", hint:"Human feeling", tags:["N3","soumatome"] },

  { kanji:"患者", reading:"かんじゃ", meaning:"patient", hint:"Person receiving treatment", tags:["N3","soumatome"] },
  { kanji:"勘違い", reading:"かんちがい", meaning:"misunderstanding", hint:"Wrong assumption", tags:["N3","soumatome"] },
  { kanji:"簡単", reading:"かんたん", meaning:"easy", hint:"Simple to do", tags:["N3","soumatome"] },
  { kanji:"完全", reading:"かんぜん", meaning:"complete", hint:"Perfect condition", tags:["N3","soumatome"] },
  { kanji:"管理", reading:"かんり", meaning:"management", hint:"Controlling properly", tags:["N3","soumatome"] },
  { kanji:"記号", reading:"きごう", meaning:"symbol", hint:"Special mark", tags:["N3","soumatome"] },
  { kanji:"機会", reading:"きかい", meaning:"opportunity", hint:"Good chance", tags:["N3","soumatome"] },
  { kanji:"危険", reading:"きけん", meaning:"danger", hint:"Unsafe situation", tags:["N3","soumatome"] },
  { kanji:"技術", reading:"ぎじゅつ", meaning:"technology / skill", hint:"Technical ability", tags:["N3","soumatome"] },
  { kanji:"季節", reading:"きせつ", meaning:"season", hint:"Time of year", tags:["N3","soumatome"] }

  { kanji:"期待", reading:"きたい", meaning:"expectation", hint:"Looking forward to something", tags:["N3","soumatome"] },
  { kanji:"気温", reading:"きおん", meaning:"temperature", hint:"Air temperature", tags:["N3","soumatome"] },
  { kanji:"気分", reading:"きぶん", meaning:"mood / feeling", hint:"Current emotional state", tags:["N3","soumatome"] },
  { kanji:"気持ち", reading:"きもち", meaning:"feeling", hint:"Emotion or sensation", tags:["N3","soumatome"] },
  { kanji:"記念", reading:"きねん", meaning:"commemoration", hint:"Remembering special event", tags:["N3","soumatome"] },
  { kanji:"記録", reading:"きろく", meaning:"record", hint:"Written history/data", tags:["N3","soumatome"] },
  { kanji:"議員", reading:"ぎいん", meaning:"assembly member", hint:"Political representative", tags:["N3","soumatome"] },
  { kanji:"技師", reading:"ぎし", meaning:"engineer", hint:"Technical specialist", tags:["N3","soumatome"] },
  { kanji:"基準", reading:"きじゅん", meaning:"standard", hint:"Reference level", tags:["N3","soumatome"] },
  { kanji:"傷", reading:"きず", meaning:"wound / injury", hint:"Physical damage", tags:["N3","soumatome"] },

  { kanji:"希望", reading:"きぼう", meaning:"hope", hint:"Desired future", tags:["N3","soumatome"] },
  { kanji:"決める", reading:"きめる", meaning:"to decide", hint:"Make decision", tags:["N3","soumatome"] },
  { kanji:"客", reading:"きゃく", meaning:"guest / customer", hint:"Visitor or buyer", tags:["N3","soumatome"] },
  { kanji:"急行", reading:"きゅうこう", meaning:"express train", hint:"Fast train service", tags:["N3","soumatome"] },
  { kanji:"急増", reading:"きゅうぞう", meaning:"rapid increase", hint:"Sudden growth", tags:["N3","soumatome"] },
  { kanji:"教育者", reading:"きょういくしゃ", meaning:"educator", hint:"Person who teaches", tags:["N3","soumatome"] },
  { kanji:"競争", reading:"きょうそう", meaning:"competition", hint:"Trying to win", tags:["N3","soumatome"] },
  { kanji:"興味", reading:"きょうみ", meaning:"interest", hint:"Curiosity about something", tags:["N3","soumatome"] },
  { kanji:"共同", reading:"きょうどう", meaning:"joint / cooperative", hint:"Done together", tags:["N3","soumatome"] },
  { kanji:"協力", reading:"きょうりょく", meaning:"cooperation", hint:"Helping together", tags:["N3","soumatome"] },

  { kanji:"許可", reading:"きょか", meaning:"permission", hint:"Allowing something", tags:["N3","soumatome"] },
  { kanji:"距離", reading:"きょり", meaning:"distance", hint:"Length between places", tags:["N3","soumatome"] },
  { kanji:"銀行", reading:"ぎんこう", meaning:"bank", hint:"Financial institution", tags:["N3","soumatome"] },
  { kanji:"金額", reading:"きんがく", meaning:"amount of money", hint:"Monetary quantity", tags:["N3","soumatome"] },
  { kanji:"緊張", reading:"きんちょう", meaning:"tension / nervousness", hint:"Feeling nervous", tags:["N3","soumatome"] },
  { kanji:"空気", reading:"くうき", meaning:"air / atmosphere", hint:"Surrounding air", tags:["N3","soumatome"] },
  { kanji:"空港", reading:"くうこう", meaning:"airport", hint:"Place for airplanes", tags:["N3","soumatome"] },
  { kanji:"偶然", reading:"ぐうぜん", meaning:"by chance", hint:"Unexpected coincidence", tags:["N3","soumatome"] },
  { kanji:"草", reading:"くさ", meaning:"grass", hint:"Green ground plant", tags:["N3","soumatome"] },
  { kanji:"比べる", reading:"くらべる", meaning:"to compare", hint:"Examine differences", tags:["N3","soumatome"] },

  { kanji:"暮らし", reading:"くらし", meaning:"living / life", hint:"Daily life style", tags:["N3","soumatome"] },
  { kanji:"暮れる", reading:"くれる", meaning:"to get dark", hint:"Day ending", tags:["N3","soumatome"] },
  { kanji:"訓練", reading:"くんれん", meaning:"training", hint:"Practice to improve", tags:["N3","soumatome"] },
  { kanji:"経験", reading:"けいけん", meaning:"experience", hint:"Knowledge from doing", tags:["N3","soumatome"] },
  { kanji:"経済", reading:"けいざい", meaning:"economy", hint:"Economic system", tags:["N3","soumatome"] },
  { kanji:"警察", reading:"けいさつ", meaning:"police", hint:"Law enforcement", tags:["N3","soumatome"] },
  { kanji:"計画", reading:"けいかく", meaning:"plan", hint:"Detailed arrangement", tags:["N3","soumatome"] },
  { kanji:"景色", reading:"けしき", meaning:"scenery", hint:"View or landscape", tags:["N3","soumatome"] },
  { kanji:"結果", reading:"けっか", meaning:"result", hint:"Outcome after action", tags:["N3","soumatome"] },
  { kanji:"決定", reading:"けってい", meaning:"decision", hint:"Final choice", tags:["N3","soumatome"] },

  { kanji:"欠席", reading:"けっせき", meaning:"absence", hint:"Not attending", tags:["N3","soumatome"] },
  { kanji:"健康", reading:"けんこう", meaning:"health", hint:"Good physical condition", tags:["N3","soumatome"] },
  { kanji:"研究", reading:"けんきゅう", meaning:"research", hint:"Careful study", tags:["N3","soumatome"] },
  { kanji:"原因", reading:"げんいん", meaning:"cause", hint:"Reason something happened", tags:["N3","soumatome"] },
  { kanji:"現金", reading:"げんきん", meaning:"cash", hint:"Physical money", tags:["N3","soumatome"] },
  { kanji:"現代", reading:"げんだい", meaning:"modern age", hint:"Present era", tags:["N3","soumatome"] },
  { kanji:"現場", reading:"げんば", meaning:"actual site", hint:"Real location", tags:["N3","soumatome"] },
  { kanji:"故障", reading:"こしょう", meaning:"breakdown", hint:"Machine failure", tags:["N3","soumatome"] },
  { kanji:"個人", reading:"こじん", meaning:"individual", hint:"Single person", tags:["N3","soumatome"] },
  { kanji:"答え", reading:"こたえ", meaning:"answer", hint:"Response to question", tags:["N3","soumatome"] }

  { kanji:"答える", reading:"こたえる", meaning:"to answer", hint:"Reply to question", tags:["N3","soumatome"] },
  { kanji:"断る", reading:"ことわる", meaning:"to refuse", hint:"Say no politely", tags:["N3","soumatome"] },
  { kanji:"異なる", reading:"ことなる", meaning:"to differ", hint:"Not be same", tags:["N3","soumatome"] },
  { kanji:"好み", reading:"このみ", meaning:"preference", hint:"Personal taste", tags:["N3","soumatome"] },
  { kanji:"困る", reading:"こまる", meaning:"to be troubled", hint:"Have difficulty", tags:["N3","soumatome"] },
  { kanji:"米", reading:"こめ", meaning:"rice", hint:"Uncooked rice grain", tags:["N3","soumatome"] },
  { kanji:"細かい", reading:"こまかい", meaning:"small / detailed", hint:"Tiny details", tags:["N3","soumatome"] },
  { kanji:"込む", reading:"こむ", meaning:"to be crowded", hint:"Filled with people", tags:["N3","soumatome"] },
  { kanji:"今後", reading:"こんご", meaning:"from now on", hint:"Future onward", tags:["N3","soumatome"] },
  { kanji:"混雑", reading:"こんざつ", meaning:"crowded", hint:"Many people together", tags:["N3","soumatome"] },

  { kanji:"最高", reading:"さいこう", meaning:"best / highest", hint:"Top quality", tags:["N3","soumatome"] },
  { kanji:"最近", reading:"さいきん", meaning:"recently", hint:"Lately", tags:["N3","soumatome"] },
  { kanji:"最後", reading:"さいご", meaning:"last", hint:"Final one", tags:["N3","soumatome"] },
  { kanji:"最初", reading:"さいしょ", meaning:"first", hint:"Beginning point", tags:["N3","soumatome"] },
  { kanji:"最低", reading:"さいてい", meaning:"worst / lowest", hint:"Very poor level", tags:["N3","soumatome"] },
  { kanji:"財布", reading:"さいふ", meaning:"wallet", hint:"Money holder", tags:["N3","soumatome"] },
  { kanji:"坂", reading:"さか", meaning:"slope / hill", hint:"Road going upward", tags:["N3","soumatome"] },
  { kanji:"探す", reading:"さがす", meaning:"to search", hint:"Look for something", tags:["N3","soumatome"] },
  { kanji:"盛ん", reading:"さかん", meaning:"prosperous / active", hint:"Very active state", tags:["N3","soumatome"] },
  { kanji:"作業", reading:"さぎょう", meaning:"work operation", hint:"Task activity", tags:["N3","soumatome"] },

  { kanji:"昨年", reading:"さくねん", meaning:"last year", hint:"Previous year", tags:["N3","soumatome"] },
  { kanji:"作品", reading:"さくひん", meaning:"work / creation", hint:"Created piece", tags:["N3","soumatome"] },
  { kanji:"作物", reading:"さくもつ", meaning:"crop", hint:"Farm-grown plant", tags:["N3","soumatome"] },
  { kanji:"支える", reading:"ささえる", meaning:"to support", hint:"Hold up", tags:["N3","soumatome"] },
  { kanji:"指す", reading:"さす", meaning:"to point", hint:"Indicate direction", tags:["N3","soumatome"] },
  { kanji:"誘う", reading:"さそう", meaning:"to invite", hint:"Ask someone to join", tags:["N3","soumatome"] },
  { kanji:"札", reading:"さつ", meaning:"bill / note", hint:"Paper money", tags:["N3","soumatome"] },
  { kanji:"寂しい", reading:"さびしい", meaning:"lonely", hint:"Feeling alone", tags:["N3","soumatome"] },
  { kanji:"騒ぐ", reading:"さわぐ", meaning:"to make noise", hint:"Be noisy", tags:["N3","soumatome"] },
  { kanji:"参加", reading:"さんか", meaning:"participation", hint:"Joining activity", tags:["N3","soumatome"] },

  { kanji:"残念", reading:"ざんねん", meaning:"regretful", hint:"Disappointing feeling", tags:["N3","soumatome"] },
  { kanji:"産業", reading:"さんぎょう", meaning:"industry", hint:"Business production field", tags:["N3","soumatome"] },
  { kanji:"賛成", reading:"さんせい", meaning:"agreement", hint:"Supporting opinion", tags:["N3","soumatome"] },
  { kanji:"使用", reading:"しよう", meaning:"use", hint:"Employ something", tags:["N3","soumatome"] },
  { kanji:"試合", reading:"しあい", meaning:"match / game", hint:"Sports competition", tags:["N3","soumatome"] },
  { kanji:"仕方", reading:"しかた", meaning:"method / way", hint:"How to do", tags:["N3","soumatome"] },
  { kanji:"試験", reading:"しけん", meaning:"exam", hint:"Test of ability", tags:["N3","soumatome"] },
  { kanji:"事故", reading:"じこ", meaning:"accident", hint:"Unexpected bad event", tags:["N3","soumatome"] },
  { kanji:"事情", reading:"じじょう", meaning:"circumstances", hint:"Background situation", tags:["N3","soumatome"] },
  { kanji:"自然", reading:"しぜん", meaning:"nature", hint:"Natural world", tags:["N3","soumatome"] },

  { kanji:"沈む", reading:"しずむ", meaning:"to sink", hint:"Go downward in water", tags:["N3","soumatome"] },
  { kanji:"静か", reading:"しずか", meaning:"quiet", hint:"Without noise", tags:["N3","soumatome"] },
  { kanji:"失敗", reading:"しっぱい", meaning:"failure", hint:"Unsuccessful result", tags:["N3","soumatome"] },
  { kanji:"質問", reading:"しつもん", meaning:"question", hint:"Something asked", tags:["N3","soumatome"] },
  { kanji:"実験", reading:"じっけん", meaning:"experiment", hint:"Scientific test", tags:["N3","soumatome"] },
  { kanji:"実際", reading:"じっさい", meaning:"actually", hint:"In reality", tags:["N3","soumatome"] },
  { kanji:"失礼", reading:"しつれい", meaning:"rude / excuse me", hint:"Polite apology phrase", tags:["N3","soumatome"] },
  { kanji:"十分", reading:"じゅうぶん", meaning:"enough", hint:"Sufficient amount", tags:["N3","soumatome"] },
  { kanji:"習慣", reading:"しゅうかん", meaning:"habit", hint:"Repeated behavior", tags:["N3","soumatome"] },
  { kanji:"住所", reading:"じゅうしょ", meaning:"address", hint:"Place of residence", tags:["N3","soumatome"] }

  { kanji:"集中", reading:"しゅうちゅう", meaning:"concentration", hint:"Focus attention strongly", tags:["N3","soumatome"] },
  { kanji:"自由", reading:"じゆう", meaning:"freedom", hint:"Able to act freely", tags:["N3","soumatome"] },
  { kanji:"修理", reading:"しゅうり", meaning:"repair", hint:"Fix broken thing", tags:["N3","soumatome"] },
  { kanji:"重要", reading:"じゅうよう", meaning:"important", hint:"Very necessary", tags:["N3","soumatome"] },
  { kanji:"授業", reading:"じゅぎょう", meaning:"class / lesson", hint:"School teaching period", tags:["N3","soumatome"] },
  { kanji:"出席", reading:"しゅっせき", meaning:"attendance", hint:"Being present", tags:["N3","soumatome"] },
  { kanji:"出発", reading:"しゅっぱつ", meaning:"departure", hint:"Leaving place", tags:["N3","soumatome"] },
  { kanji:"出張", reading:"しゅっちょう", meaning:"business trip", hint:"Work-related travel", tags:["N3","soumatome"] },
  { kanji:"趣味", reading:"しゅみ", meaning:"hobby", hint:"Favorite pastime", tags:["N3","soumatome"] },
  { kanji:"紹介", reading:"しょうかい", meaning:"introduction", hint:"Presenting someone", tags:["N3","soumatome"] },

  { kanji:"小説", reading:"しょうせつ", meaning:"novel", hint:"Long fictional story", tags:["N3","soumatome"] },
  { kanji:"消える", reading:"きえる", meaning:"to disappear", hint:"No longer visible", tags:["N3","soumatome"] },
  { kanji:"消す", reading:"けす", meaning:"to erase / turn off", hint:"Remove something", tags:["N3","soumatome"] },
  { kanji:"商品", reading:"しょうひん", meaning:"product", hint:"Goods for sale", tags:["N3","soumatome"] },
  { kanji:"消防署", reading:"しょうぼうしょ", meaning:"fire station", hint:"Place for firefighters", tags:["N3","soumatome"] },
  { kanji:"情報", reading:"じょうほう", meaning:"information", hint:"Useful data", tags:["N3","soumatome"] },
  { kanji:"証明", reading:"しょうめい", meaning:"proof / certificate", hint:"Evidence of truth", tags:["N3","soumatome"] },
  { kanji:"招待", reading:"しょうたい", meaning:"invitation", hint:"Request to attend", tags:["N3","soumatome"] },
  { kanji:"状態", reading:"じょうたい", meaning:"condition / state", hint:"Current situation", tags:["N3","soumatome"] },
  { kanji:"食事", reading:"しょくじ", meaning:"meal", hint:"Eating food", tags:["N3","soumatome"] },

  { kanji:"食堂", reading:"しょくどう", meaning:"cafeteria", hint:"Place to eat", tags:["N3","soumatome"] },
  { kanji:"植物", reading:"しょくぶつ", meaning:"plant", hint:"Living green organism", tags:["N3","soumatome"] },
  { kanji:"知らせる", reading:"しらせる", meaning:"to inform", hint:"Tell information", tags:["N3","soumatome"] },
  { kanji:"調べる", reading:"しらべる", meaning:"to investigate", hint:"Check carefully", tags:["N3","soumatome"] },
  { kanji:"進学", reading:"しんがく", meaning:"enter higher school", hint:"Continue education", tags:["N3","soumatome"] },
  { kanji:"進む", reading:"すすむ", meaning:"to advance", hint:"Move forward", tags:["N3","soumatome"] },
  { kanji:"親切", reading:"しんせつ", meaning:"kindness", hint:"Helpful attitude", tags:["N3","soumatome"] },
  { kanji:"信号", reading:"しんごう", meaning:"traffic light", hint:"Road signal", tags:["N3","soumatome"] },
  { kanji:"心配", reading:"しんぱい", meaning:"worry", hint:"Feeling anxiety", tags:["N3","soumatome"] },
  { kanji:"新聞", reading:"しんぶん", meaning:"newspaper", hint:"Printed news", tags:["N3","soumatome"] },

  { kanji:"水準", reading:"すいじゅん", meaning:"level / standard", hint:"Quality measurement", tags:["N3","soumatome"] },
  { kanji:"水道", reading:"すいどう", meaning:"water supply", hint:"Tap water system", tags:["N3","soumatome"] },
  { kanji:"数字", reading:"すうじ", meaning:"number", hint:"Numerical symbol", tags:["N3","soumatome"] },
  { kanji:"過ぎる", reading:"すぎる", meaning:"to pass / exceed", hint:"Go beyond limit", tags:["N3","soumatome"] },
  { kanji:"進める", reading:"すすめる", meaning:"to proceed", hint:"Move something ahead", tags:["N3","soumatome"] },
  { kanji:"捨てる", reading:"すてる", meaning:"to throw away", hint:"Discard something", tags:["N3","soumatome"] },
  { kanji:"砂", reading:"すな", meaning:"sand", hint:"Tiny grains", tags:["N3","soumatome"] },
  { kanji:"全て", reading:"すべて", meaning:"all", hint:"Everything included", tags:["N3","soumatome"] },
  { kanji:"済む", reading:"すむ", meaning:"to finish", hint:"Be completed", tags:["N3","soumatome"] },
  { kanji:"生活", reading:"せいかつ", meaning:"daily life", hint:"Everyday living", tags:["N3","soumatome"] },

  { kanji:"政治", reading:"せいじ", meaning:"politics", hint:"Government activities", tags:["N3","soumatome"] },
  { kanji:"成績", reading:"せいせき", meaning:"grades / results", hint:"Academic performance", tags:["N3","soumatome"] },
  { kanji:"成長", reading:"せいちょう", meaning:"growth", hint:"Becoming bigger", tags:["N3","soumatome"] },
  { kanji:"制度", reading:"せいど", meaning:"system", hint:"Organized structure", tags:["N3","soumatome"] },
  { kanji:"整理", reading:"せいり", meaning:"organization", hint:"Putting in order", tags:["N3","soumatome"] },
  { kanji:"説明", reading:"せつめい", meaning:"explanation", hint:"Clarifying details", tags:["N3","soumatome"] },
  { kanji:"世話", reading:"せわ", meaning:"care", hint:"Helping someone", tags:["N3","soumatome"] },
  { kanji:"選ぶ", reading:"えらぶ", meaning:"to choose", hint:"Pick one option", tags:["N3","soumatome"] },
  { kanji:"専門", reading:"せんもん", meaning:"specialty", hint:"Area of expertise", tags:["N3","soumatome"] },
  { kanji:"戦争", reading:"せんそう", meaning:"war", hint:"Armed conflict", tags:["N3","soumatome"] }

  { kanji:"洗濯", reading:"せんたく", meaning:"laundry", hint:"Washing clothes", tags:["N3","soumatome"] },
  { kanji:"全部", reading:"ぜんぶ", meaning:"all", hint:"Everything together", tags:["N3","soumatome"] },
  { kanji:"相当", reading:"そうとう", meaning:"considerable", hint:"Quite a lot", tags:["N3","soumatome"] },
  { kanji:"相談", reading:"そうだん", meaning:"consultation", hint:"Discussing worries", tags:["N3","soumatome"] },
  { kanji:"増加", reading:"ぞうか", meaning:"increase", hint:"Become larger", tags:["N3","soumatome"] },
  { kanji:"掃除", reading:"そうじ", meaning:"cleaning", hint:"Removing dirt", tags:["N3","soumatome"] },
  { kanji:"想像", reading:"そうぞう", meaning:"imagination", hint:"Creating in mind", tags:["N3","soumatome"] },
  { kanji:"速達", reading:"そくたつ", meaning:"express delivery", hint:"Fast mail service", tags:["N3","soumatome"] },
  { kanji:"卒業", reading:"そつぎょう", meaning:"graduation", hint:"Finishing school", tags:["N3","soumatome"] },
  { kanji:"育つ", reading:"そだつ", meaning:"to grow", hint:"Become bigger naturally", tags:["N3","soumatome"] },

  { kanji:"育てる", reading:"そだてる", meaning:"to raise", hint:"Bring up child/plant", tags:["N3","soumatome"] },
  { kanji:"相談室", reading:"そうだんしつ", meaning:"consultation room", hint:"Room for advice", tags:["N3","soumatome"] },
  { kanji:"存在", reading:"そんざい", meaning:"existence", hint:"Being present", tags:["N3","soumatome"] },
  { kanji:"大切", reading:"たいせつ", meaning:"important / valuable", hint:"Precious thing", tags:["N3","soumatome"] },
  { kanji:"大変", reading:"たいへん", meaning:"difficult / serious", hint:"Hard situation", tags:["N3","soumatome"] },
  { kanji:"倒れる", reading:"たおれる", meaning:"to collapse", hint:"Fall down", tags:["N3","soumatome"] },
  { kanji:"確か", reading:"たしか", meaning:"certain", hint:"Probably correct", tags:["N3","soumatome"] },
  { kanji:"助かる", reading:"たすかる", meaning:"to be saved", hint:"Escape danger", tags:["N3","soumatome"] },
  { kanji:"訪ねる", reading:"たずねる", meaning:"to visit", hint:"Go see someone", tags:["N3","soumatome"] },
  { kanji:"戦う", reading:"たたかう", meaning:"to fight", hint:"Battle against", tags:["N3","soumatome"] },

  { kanji:"叩く", reading:"たたく", meaning:"to hit", hint:"Strike something", tags:["N3","soumatome"] },
  { kanji:"畳", reading:"たたみ", meaning:"tatami mat", hint:"Traditional Japanese flooring", tags:["N3","soumatome"] },
  { kanji:"例えば", reading:"たとえば", meaning:"for example", hint:"Giving example", tags:["N3","soumatome"] },
  { kanji:"頼む", reading:"たのむ", meaning:"to request", hint:"Ask favor", tags:["N3","soumatome"] },
  { kanji:"楽しみ", reading:"たのしみ", meaning:"looking forward to", hint:"Pleasant expectation", tags:["N3","soumatome"] },
  { kanji:"足りる", reading:"たりる", meaning:"to be enough", hint:"Sufficient amount", tags:["N3","soumatome"] },
  { kanji:"段階", reading:"だんかい", meaning:"stage / level", hint:"Step in process", tags:["N3","soumatome"] },
  { kanji:"男性", reading:"だんせい", meaning:"male", hint:"Adult man", tags:["N3","soumatome"] },
  { kanji:"暖房", reading:"だんぼう", meaning:"heating", hint:"Room warming system", tags:["N3","soumatome"] },
  { kanji:"地域", reading:"ちいき", meaning:"region", hint:"Specific area", tags:["N3","soumatome"] },

  { kanji:"知識", reading:"ちしき", meaning:"knowledge", hint:"Information learned", tags:["N3","soumatome"] },
  { kanji:"遅刻", reading:"ちこく", meaning:"lateness", hint:"Arriving late", tags:["N3","soumatome"] },
  { kanji:"地図", reading:"ちず", meaning:"map", hint:"Drawing of area", tags:["N3","soumatome"] },
  { kanji:"注意", reading:"ちゅうい", meaning:"caution", hint:"Carefulness", tags:["N3","soumatome"] },
  { kanji:"中心", reading:"ちゅうしん", meaning:"center", hint:"Middle point", tags:["N3","soumatome"] },
  { kanji:"駐車場", reading:"ちゅうしゃじょう", meaning:"parking lot", hint:"Place for cars", tags:["N3","soumatome"] },
  { kanji:"直接", reading:"ちょくせつ", meaning:"directly", hint:"Without middle step", tags:["N3","soumatome"] },
  { kanji:"貯金", reading:"ちょきん", meaning:"savings", hint:"Money stored", tags:["N3","soumatome"] },
  { kanji:"丁寧", reading:"ていねい", meaning:"polite / careful", hint:"Respectful manner", tags:["N3","soumatome"] },
  { kanji:"手術", reading:"しゅじゅつ", meaning:"surgery", hint:"Medical operation", tags:["N3","soumatome"] },

  { kanji:"適当", reading:"てきとう", meaning:"appropriate", hint:"Suitable condition", tags:["N3","soumatome"] },
  { kanji:"鉄道", reading:"てつどう", meaning:"railway", hint:"Train transportation", tags:["N3","soumatome"] },
  { kanji:"手伝う", reading:"てつだう", meaning:"to help", hint:"Assist someone", tags:["N3","soumatome"] },
  { kanji:"届ける", reading:"とどける", meaning:"to deliver", hint:"Bring to destination", tags:["N3","soumatome"] },
  { kanji:"途中", reading:"とちゅう", meaning:"on the way", hint:"Middle of route", tags:["N3","soumatome"] },
  { kanji:"特別", reading:"とくべつ", meaning:"special", hint:"Different from usual", tags:["N3","soumatome"] },
  { kanji:"得意", reading:"とくい", meaning:"good at", hint:"Skilled in something", tags:["N3","soumatome"] },
  { kanji:"独身", reading:"どくしん", meaning:"single", hint:"Not married", tags:["N3","soumatome"] },
  { kanji:"突然", reading:"とつぜん", meaning:"suddenly", hint:"Without warning", tags:["N3","soumatome"] },
  { kanji:"届く", reading:"とどく", meaning:"to arrive", hint:"Reach destination", tags:["N3","soumatome"] }

  { kanji:"泊まる", reading:"とまる", meaning:"to stay overnight", hint:"Sleep somewhere temporarily", tags:["N3","soumatome"] },
  { kanji:"止める", reading:"とめる", meaning:"to stop", hint:"Bring to halt", tags:["N3","soumatome"] },
  { kanji:"友達", reading:"ともだち", meaning:"friend", hint:"Close companion", tags:["N3","soumatome"] },
  { kanji:"努力", reading:"どりょく", meaning:"effort", hint:"Hard work", tags:["N3","soumatome"] },
  { kanji:"泣く", reading:"なく", meaning:"to cry", hint:"Tears come out", tags:["N3","soumatome"] },
  { kanji:"亡くなる", reading:"なくなる", meaning:"to pass away", hint:"Person dies", tags:["N3","soumatome"] },
  { kanji:"投げる", reading:"なげる", meaning:"to throw", hint:"Send through air", tags:["N3","soumatome"] },
  { kanji:"無くす", reading:"なくす", meaning:"to lose", hint:"Cannot find anymore", tags:["N3","soumatome"] },
  { kanji:"流れる", reading:"ながれる", meaning:"to flow", hint:"Move like water", tags:["N3","soumatome"] },
  { kanji:"泣き声", reading:"なきごえ", meaning:"crying voice", hint:"Sound of crying", tags:["N3","soumatome"] },

  { kanji:"仲間", reading:"なかま", meaning:"companion", hint:"Member of same group", tags:["N3","soumatome"] },
  { kanji:"長生き", reading:"ながいき", meaning:"long life", hint:"Living many years", tags:["N3","soumatome"] },
  { kanji:"眺め", reading:"ながめ", meaning:"view / scenery", hint:"Scene seen from place", tags:["N3","soumatome"] },
  { kanji:"殴る", reading:"なぐる", meaning:"to punch", hint:"Hit with fist", tags:["N3","soumatome"] },
  { kanji:"亡くす", reading:"なくす", meaning:"to lose someone by death", hint:"Person passes away", tags:["N3","soumatome"] },
  { kanji:"投げ捨てる", reading:"なげすてる", meaning:"to throw away", hint:"Discard carelessly", tags:["N3","soumatome"] },
  { kanji:"懐かしい", reading:"なつかしい", meaning:"nostalgic", hint:"Remember old times fondly", tags:["N3","soumatome"] },
  { kanji:"納得", reading:"なっとく", meaning:"consent / understanding", hint:"Accept after understanding", tags:["N3","soumatome"] },
  { kanji:"鍋", reading:"なべ", meaning:"pot", hint:"Cooking container", tags:["N3","soumatome"] },
  { kanji:"生", reading:"なま", meaning:"raw / fresh", hint:"Uncooked state", tags:["N3","soumatome"] },

  { kanji:"慣れる", reading:"なれる", meaning:"to get used to", hint:"Become accustomed", tags:["N3","soumatome"] },
  { kanji:"苦い", reading:"にがい", meaning:"bitter", hint:"Strong unpleasant taste", tags:["N3","soumatome"] },
  { kanji:"逃げる", reading:"にげる", meaning:"to escape", hint:"Run away", tags:["N3","soumatome"] },
  { kanji:"日記", reading:"にっき", meaning:"diary", hint:"Daily written record", tags:["N3","soumatome"] },
  { kanji:"入学", reading:"にゅうがく", meaning:"school entrance", hint:"Entering school", tags:["N3","soumatome"] },
  { kanji:"人気", reading:"にんき", meaning:"popularity", hint:"Liked by many", tags:["N3","soumatome"] },
  { kanji:"人形", reading:"にんぎょう", meaning:"doll", hint:"Toy shaped like person", tags:["N3","soumatome"] },
  { kanji:"願う", reading:"ねがう", meaning:"to wish", hint:"Hope strongly", tags:["N3","soumatome"] },
  { kanji:"熱", reading:"ねつ", meaning:"fever / heat", hint:"High body temperature", tags:["N3","soumatome"] },
  { kanji:"熱心", reading:"ねっしん", meaning:"enthusiastic", hint:"Very eager", tags:["N3","soumatome"] },

  { kanji:"値段", reading:"ねだん", meaning:"price", hint:"Cost of item", tags:["N3","soumatome"] },
  { kanji:"眠る", reading:"ねむる", meaning:"to sleep", hint:"Rest with eyes closed", tags:["N3","soumatome"] },
  { kanji:"残る", reading:"のこる", meaning:"to remain", hint:"Stay behind", tags:["N3","soumatome"] },
  { kanji:"残す", reading:"のこす", meaning:"to leave behind", hint:"Keep remaining", tags:["N3","soumatome"] },
  { kanji:"乗り換える", reading:"のりかえる", meaning:"to transfer", hint:"Change trains/buses", tags:["N3","soumatome"] },
  { kanji:"乗り物", reading:"のりもの", meaning:"vehicle", hint:"Transportation machine", tags:["N3","soumatome"] },
  { kanji:"農業", reading:"のうぎょう", meaning:"agriculture", hint:"Farming industry", tags:["N3","soumatome"] },
  { kanji:"能力", reading:"のうりょく", meaning:"ability", hint:"Skill or power", tags:["N3","soumatome"] },
  { kanji:"伸ばす", reading:"のばす", meaning:"to extend", hint:"Make longer", tags:["N3","soumatome"] },
  { kanji:"延びる", reading:"のびる", meaning:"to stretch", hint:"Become longer", tags:["N3","soumatome"] },

  { kanji:"登る", reading:"のぼる", meaning:"to climb", hint:"Go upward", tags:["N3","soumatome"] },
  { kanji:"飲み物", reading:"のみもの", meaning:"drink", hint:"Liquid beverage", tags:["N3","soumatome"] },
  { kanji:"乗せる", reading:"のせる", meaning:"to place on", hint:"Put onto surface", tags:["N3","soumatome"] },
  { kanji:"歯医者", reading:"はいしゃ", meaning:"dentist", hint:"Tooth doctor", tags:["N3","soumatome"] },
  { kanji:"配達", reading:"はいたつ", meaning:"delivery", hint:"Transporting items", tags:["N3","soumatome"] },
  { kanji:"場合", reading:"ばあい", meaning:"case / situation", hint:"Particular condition", tags:["N3","soumatome"] },
  { kanji:"売店", reading:"ばいてん", meaning:"shop stall", hint:"Small store", tags:["N3","soumatome"] },
  { kanji:"博士", reading:"はかせ", meaning:"expert / doctor", hint:"Highly educated person", tags:["N3","soumatome"] },
  { kanji:"拍手", reading:"はくしゅ", meaning:"applause", hint:"Clapping hands", tags:["N3","soumatome"] },
  { kanji:"始まる", reading:"はじまる", meaning:"to begin", hint:"Something starts", tags:["N3","soumatome"] }

  { kanji:"始める", reading:"はじめる", meaning:"to begin", hint:"Start doing something", tags:["N3","soumatome"] },
  { kanji:"場所", reading:"ばしょ", meaning:"place", hint:"Location or area", tags:["N3","soumatome"] },
  { kanji:"走る", reading:"はしる", meaning:"to run", hint:"Move quickly on foot", tags:["N3","soumatome"] },
  { kanji:"恥ずかしい", reading:"はずかしい", meaning:"embarrassed", hint:"Feeling ashamed", tags:["N3","soumatome"] },
  { kanji:"働く", reading:"はたらく", meaning:"to work", hint:"Do job or labor", tags:["N3","soumatome"] },
  { kanji:"発音", reading:"はつおん", meaning:"pronunciation", hint:"Way of speaking sounds", tags:["N3","soumatome"] },
  { kanji:"発見", reading:"はっけん", meaning:"discovery", hint:"Finding something new", tags:["N3","soumatome"] },
  { kanji:"発車", reading:"はっしゃ", meaning:"departure of vehicle", hint:"Train/bus leaving", tags:["N3","soumatome"] },
  { kanji:"発表", reading:"はっぴょう", meaning:"announcement / presentation", hint:"Publicly showing information", tags:["N3","soumatome"] },
  { kanji:"花見", reading:"はなみ", meaning:"flower viewing", hint:"Cherry blossom viewing", tags:["N3","soumatome"] },

  { kanji:"離れる", reading:"はなれる", meaning:"to separate", hint:"Move away from", tags:["N3","soumatome"] },
  { kanji:"払う", reading:"はらう", meaning:"to pay", hint:"Give money", tags:["N3","soumatome"] },
  { kanji:"番組", reading:"ばんぐみ", meaning:"TV/radio program", hint:"Broadcast show", tags:["N3","soumatome"] },
  { kanji:"反対", reading:"はんたい", meaning:"opposition", hint:"Against something", tags:["N3","soumatome"] },
  { kanji:"判断", reading:"はんだん", meaning:"judgment", hint:"Making decision", tags:["N3","soumatome"] },
  { kanji:"販売", reading:"はんばい", meaning:"sales", hint:"Selling products", tags:["N3","soumatome"] },
  { kanji:"必要", reading:"ひつよう", meaning:"necessary", hint:"Needed thing", tags:["N3","soumatome"] },
  { kanji:"引き出し", reading:"ひきだし", meaning:"drawer", hint:"Sliding storage space", tags:["N3","soumatome"] },
  { kanji:"引き出す", reading:"ひきだす", meaning:"to withdraw / pull out", hint:"Take out something", tags:["N3","soumatome"] },
  { kanji:"比較", reading:"ひかく", meaning:"comparison", hint:"Comparing differences", tags:["N3","soumatome"] },

  { kanji:"光", reading:"ひかり", meaning:"light", hint:"Brightness", tags:["N3","soumatome"] },
  { kanji:"光る", reading:"ひかる", meaning:"to shine", hint:"Give off light", tags:["N3","soumatome"] },
  { kanji:"久しぶり", reading:"ひさしぶり", meaning:"after long time", hint:"Not seen recently", tags:["N3","soumatome"] },
  { kanji:"非常", reading:"ひじょう", meaning:"emergency", hint:"Urgent unusual situation", tags:["N3","soumatome"] },
  { kanji:"必要性", reading:"ひつようせい", meaning:"necessity", hint:"Degree of being needed", tags:["N3","soumatome"] },
  { kanji:"一人暮らし", reading:"ひとりぐらし", meaning:"living alone", hint:"Independent living", tags:["N3","soumatome"] },
  { kanji:"秘密", reading:"ひみつ", meaning:"secret", hint:"Hidden information", tags:["N3","soumatome"] },
  { kanji:"表現", reading:"ひょうげん", meaning:"expression", hint:"Way of expressing", tags:["N3","soumatome"] },
  { kanji:"評価", reading:"ひょうか", meaning:"evaluation", hint:"Judging quality", tags:["N3","soumatome"] },
  { kanji:"平和", reading:"へいわ", meaning:"peace", hint:"No conflict", tags:["N3","soumatome"] },

  { kanji:"別れる", reading:"わかれる", meaning:"to separate", hint:"Go different ways", tags:["N3","soumatome"] },
  { kanji:"変化", reading:"へんか", meaning:"change", hint:"Becoming different", tags:["N3","soumatome"] },
  { kanji:"返事", reading:"へんじ", meaning:"reply", hint:"Answer to someone", tags:["N3","soumatome"] },
  { kanji:"勉強", reading:"べんきょう", meaning:"study", hint:"Learning activity", tags:["N3","soumatome"] },
  { kanji:"貿易", reading:"ぼうえき", meaning:"trade", hint:"Business between countries", tags:["N3","soumatome"] },
  { kanji:"法律", reading:"ほうりつ", meaning:"law", hint:"Rules of society", tags:["N3","soumatome"] },
  { kanji:"放送", reading:"ほうそう", meaning:"broadcast", hint:"TV/radio transmission", tags:["N3","soumatome"] },
  { kanji:"訪問", reading:"ほうもん", meaning:"visit", hint:"Going to see someone", tags:["N3","soumatome"] },
  { kanji:"方法", reading:"ほうほう", meaning:"method", hint:"Way of doing", tags:["N3","soumatome"] },
  { kanji:"保存", reading:"ほぞん", meaning:"preservation / save", hint:"Keep safely", tags:["N3","soumatome"] },

  { kanji:"星", reading:"ほし", meaning:"star", hint:"Celestial object", tags:["N3","soumatome"] },
  { kanji:"細い", reading:"ほそい", meaning:"thin", hint:"Small width", tags:["N3","soumatome"] },
  { kanji:"ほとんど", reading:"ほとんど", meaning:"almost", hint:"Nearly all", tags:["N3","soumatome"] },
  { kanji:"翻訳", reading:"ほんやく", meaning:"translation", hint:"Changing language", tags:["N3","soumatome"] },
  { kanji:"本屋", reading:"ほんや", meaning:"bookstore", hint:"Shop selling books", tags:["N3","soumatome"] },
  { kanji:"間違い", reading:"まちがい", meaning:"mistake", hint:"Wrong answer/action", tags:["N3","soumatome"] },
  { kanji:"間に合う", reading:"まにあう", meaning:"to be in time", hint:"Arrive before deadline", tags:["N3","soumatome"] },
  { kanji:"守る", reading:"まもる", meaning:"to protect", hint:"Keep safe", tags:["N3","soumatome"] },
  { kanji:"迷う", reading:"まよう", meaning:"to be confused / lost", hint:"Cannot decide direction", tags:["N3","soumatome"] },
  { kanji:"満足", reading:"まんぞく", meaning:"satisfaction", hint:"Feeling content", tags:["N3","soumatome"] }

  { kanji:"見送り", reading:"みおくり", meaning:"seeing off", hint:"Watching someone leave", tags:["N3","soumatome"] },
  { kanji:"見つかる", reading:"みつかる", meaning:"to be found", hint:"Become discovered", tags:["N3","soumatome"] },
  { kanji:"見つける", reading:"みつける", meaning:"to find", hint:"Discover something", tags:["N3","soumatome"] },
  { kanji:"港", reading:"みなと", meaning:"harbor", hint:"Place for ships", tags:["N3","soumatome"] },
  { kanji:"迎える", reading:"むかえる", meaning:"to welcome", hint:"Receive someone warmly", tags:["N3","soumatome"] },
  { kanji:"昔", reading:"むかし", meaning:"old times", hint:"Long ago", tags:["N3","soumatome"] },
  { kanji:"無理", reading:"むり", meaning:"impossible / unreasonable", hint:"Too difficult", tags:["N3","soumatome"] },
  { kanji:"珍しい", reading:"めずらしい", meaning:"rare", hint:"Not common", tags:["N3","soumatome"] },
  { kanji:"目的", reading:"もくてき", meaning:"purpose", hint:"Reason for doing", tags:["N3","soumatome"] },
  { kanji:"戻る", reading:"もどる", meaning:"to return", hint:"Go back", tags:["N3","soumatome"] },

  { kanji:"木綿", reading:"もめん", meaning:"cotton", hint:"Cotton fabric", tags:["N3","soumatome"] },
  { kanji:"問題", reading:"もんだい", meaning:"problem / question", hint:"Thing needing solution", tags:["N3","soumatome"] },
  { kanji:"約束", reading:"やくそく", meaning:"promise", hint:"Agreement between people", tags:["N3","soumatome"] },
  { kanji:"役に立つ", reading:"やくにたつ", meaning:"to be useful", hint:"Helpful thing", tags:["N3","soumatome"] },
  { kanji:"焼ける", reading:"やける", meaning:"to burn / bake", hint:"Affected by fire/heat", tags:["N3","soumatome"] },
  { kanji:"優しい", reading:"やさしい", meaning:"kind", hint:"Gentle personality", tags:["N3","soumatome"] },
  { kanji:"痩せる", reading:"やせる", meaning:"to lose weight", hint:"Become thinner", tags:["N3","soumatome"] },
  { kanji:"約", reading:"やく", meaning:"about / approximately", hint:"Rough amount", tags:["N3","soumatome"] },
  { kanji:"役所", reading:"やくしょ", meaning:"government office", hint:"Public administration office", tags:["N3","soumatome"] },
  { kanji:"休み", reading:"やすみ", meaning:"rest / holiday", hint:"Time off", tags:["N3","soumatome"] },

  { kanji:"休む", reading:"やすむ", meaning:"to rest", hint:"Take break", tags:["N3","soumatome"] },
  { kanji:"安い", reading:"やすい", meaning:"cheap", hint:"Low price", tags:["N3","soumatome"] },
  { kanji:"痩せた", reading:"やせた", meaning:"thin", hint:"Having lost weight", tags:["N3","soumatome"] },
  { kanji:"輸出", reading:"ゆしゅつ", meaning:"export", hint:"Send goods abroad", tags:["N3","soumatome"] },
  { kanji:"輸入", reading:"ゆにゅう", meaning:"import", hint:"Bring goods from abroad", tags:["N3","soumatome"] },
  { kanji:"夢", reading:"ゆめ", meaning:"dream", hint:"Vision during sleep", tags:["N3","soumatome"] },
  { kanji:"揺れる", reading:"ゆれる", meaning:"to shake", hint:"Move side to side", tags:["N3","soumatome"] },
  { kanji:"用", reading:"よう", meaning:"business / errand", hint:"Purpose or task", tags:["N3","soumatome"] },
  { kanji:"用事", reading:"ようじ", meaning:"errand", hint:"Task to do", tags:["N3","soumatome"] },
  { kanji:"用意", reading:"ようい", meaning:"preparation", hint:"Getting ready", tags:["N3","soumatome"] },

  { kanji:"汚れる", reading:"よごれる", meaning:"to become dirty", hint:"Lose cleanliness", tags:["N3","soumatome"] },
  { kanji:"予習", reading:"よしゅう", meaning:"preparation study", hint:"Study before class", tags:["N3","soumatome"] },
  { kanji:"予定", reading:"よてい", meaning:"schedule / plan", hint:"Planned arrangement", tags:["N3","soumatome"] },
  { kanji:"予約", reading:"よやく", meaning:"reservation", hint:"Booking beforehand", tags:["N3","soumatome"] },
  { kanji:"喜ぶ", reading:"よろこぶ", meaning:"to be delighted", hint:"Feel happiness", tags:["N3","soumatome"] },
  { kanji:"理由", reading:"りゆう", meaning:"reason", hint:"Cause or explanation", tags:["N3","soumatome"] },
  { kanji:"利用", reading:"りよう", meaning:"use / utilization", hint:"Using something", tags:["N3","soumatome"] },
  { kanji:"留学", reading:"りゅうがく", meaning:"study abroad", hint:"Learning in foreign country", tags:["N3","soumatome"] },
  { kanji:"両方", reading:"りょうほう", meaning:"both", hint:"Two sides together", tags:["N3","soumatome"] },
  { kanji:"旅行", reading:"りょこう", meaning:"travel", hint:"Trip to another place", tags:["N3","soumatome"] },

  { kanji:"連絡", reading:"れんらく", meaning:"contact", hint:"Communication with someone", tags:["N3","soumatome"] },
  { kanji:"練習", reading:"れんしゅう", meaning:"practice", hint:"Repeated training", tags:["N3","soumatome"] },
  { kanji:"歴史", reading:"れきし", meaning:"history", hint:"Past events", tags:["N3","soumatome"] },
  { kanji:"冷房", reading:"れいぼう", meaning:"air conditioning", hint:"Cooling system", tags:["N3","soumatome"] },
  { kanji:"列車", reading:"れっしゃ", meaning:"train", hint:"Railway vehicle", tags:["N3","soumatome"] },
  { kanji:"連れて行く", reading:"つれていく", meaning:"to take someone along", hint:"Go together with person", tags:["N3","soumatome"] },
  { kanji:"練習問題", reading:"れんしゅうもんだい", meaning:"practice problem", hint:"Question for practice", tags:["N3","soumatome"] },
  { kanji:"老人", reading:"ろうじん", meaning:"elderly person", hint:"Old person", tags:["N3","soumatome"] },
  { kanji:"労働", reading:"ろうどう", meaning:"labor", hint:"Physical or mental work", tags:["N3","soumatome"] },
  { kanji:"笑う", reading:"わらう", meaning:"to laugh", hint:"Express happiness", tags:["N3","soumatome"] }

  { kanji:"割合", reading:"わりあい", meaning:"rate / ratio", hint:"Proportion amount", tags:["N3","soumatome"] },
  { kanji:"割れる", reading:"われる", meaning:"to break / split", hint:"Crack into pieces", tags:["N3","soumatome"] },
  { kanji:"渡す", reading:"わたす", meaning:"to hand over", hint:"Give directly", tags:["N3","soumatome"] },
  { kanji:"渡る", reading:"わたる", meaning:"to cross", hint:"Move across area", tags:["N3","soumatome"] },
  { kanji:"忘れ物", reading:"わすれもの", meaning:"forgotten item", hint:"Thing left behind", tags:["N3","soumatome"] },
  { kanji:"若い", reading:"わかい", meaning:"young", hint:"Not old", tags:["N3","soumatome"] },
  { kanji:"分かる", reading:"わかる", meaning:"to understand", hint:"Comprehend meaning", tags:["N3","soumatome"] },
  { kanji:"別れる", reading:"わかれる", meaning:"to separate", hint:"Go different ways", tags:["N3","soumatome"] },
  { kanji:"沸かす", reading:"わかす", meaning:"to boil", hint:"Heat liquid", tags:["N3","soumatome"] },
  { kanji:"沸く", reading:"わく", meaning:"to boil", hint:"Liquid becomes hot", tags:["N3","soumatome"] },

  { kanji:"訳", reading:"わけ", meaning:"reason", hint:"Explanation or cause", tags:["N3","soumatome"] },
  { kanji:"忘れる", reading:"わすれる", meaning:"to forget", hint:"Fail to remember", tags:["N3","soumatome"] },
  { kanji:"割合的", reading:"わりあいてき", meaning:"comparatively", hint:"Relatively speaking", tags:["N3","soumatome"] },
  { kanji:"笑顔", reading:"えがお", meaning:"smiling face", hint:"Happy expression", tags:["N3","soumatome"] },
  { kanji:"和室", reading:"わしつ", meaning:"Japanese-style room", hint:"Tatami room", tags:["N3","soumatome"] },
  { kanji:"和食", reading:"わしょく", meaning:"Japanese food", hint:"Traditional cuisine", tags:["N3","soumatome"] },
  { kanji:"和服", reading:"わふく", meaning:"Japanese clothing", hint:"Kimono-style clothes", tags:["N3","soumatome"] },
  { kanji:"割合表", reading:"わりあいひょう", meaning:"ratio chart", hint:"Graph showing proportions", tags:["N3","soumatome"] },
  { kanji:"割引", reading:"わりびき", meaning:"discount", hint:"Reduced price", tags:["N3","soumatome"] },
  { kanji:"割合計算", reading:"わりあいけいさん", meaning:"ratio calculation", hint:"Math involving proportions", tags:["N3","soumatome"] },

  { kanji:"忘年会", reading:"ぼうねんかい", meaning:"year-end party", hint:"End of year gathering", tags:["N3","soumatome"] },
  { kanji:"割合問題", reading:"わりあいもんだい", meaning:"ratio problem", hint:"Math ratio question", tags:["N3","soumatome"] },
  { kanji:"和風", reading:"わふう", meaning:"Japanese style", hint:"Traditional Japanese design", tags:["N3","soumatome"] },
  { kanji:"和やか", reading:"なごやか", meaning:"peaceful / harmonious", hint:"Gentle atmosphere", tags:["N3","soumatome"] },
  { kanji:"和紙", reading:"わし", meaning:"Japanese paper", hint:"Traditional handmade paper", tags:["N3","soumatome"] },
  { kanji:"割合分布", reading:"わりあいぶんぷ", meaning:"ratio distribution", hint:"Distribution by percentage", tags:["N3","soumatome"] },
  { kanji:"割り算", reading:"わりざん", meaning:"division", hint:"Math division operation", tags:["N3","soumatome"] },
  { kanji:"割合変化", reading:"わりあいへんか", meaning:"ratio change", hint:"Change in percentage", tags:["N3","soumatome"] },
  { kanji:"割る", reading:"わる", meaning:"to divide / break", hint:"Split into parts", tags:["N3","soumatome"] },
  { kanji:"悪口", reading:"わるぐち", meaning:"bad-mouthing", hint:"Speaking badly of others", tags:["N3","soumatome"] },

  { kanji:"割合比較", reading:"わりあいひかく", meaning:"ratio comparison", hint:"Comparing percentages", tags:["N3","soumatome"] },
  { kanji:"割合分析", reading:"わりあいぶんせき", meaning:"ratio analysis", hint:"Analyzing proportions", tags:["N3","soumatome"] },
  { kanji:"割合調査", reading:"わりあいちょうさ", meaning:"ratio survey", hint:"Survey using percentages", tags:["N3","soumatome"] },
  { kanji:"割合結果", reading:"わりあいけっか", meaning:"ratio result", hint:"Outcome in percentages", tags:["N3","soumatome"] },
  { kanji:"割合変動", reading:"わりあいへんどう", meaning:"ratio fluctuation", hint:"Changing percentage values", tags:["N3","soumatome"] },
  { kanji:"割合増加", reading:"わりあいぞうか", meaning:"ratio increase", hint:"Increase by percentage", tags:["N3","soumatome"] },
  { kanji:"割合減少", reading:"わりあいげんしょう", meaning:"ratio decrease", hint:"Decrease by percentage", tags:["N3","soumatome"] },
  { kanji:"割合管理", reading:"わりあいかんり", meaning:"ratio management", hint:"Managing proportions", tags:["N3","soumatome"] },
  { kanji:"割合確認", reading:"わりあいかくにん", meaning:"ratio confirmation", hint:"Checking proportions", tags:["N3","soumatome"] },
  { kanji:"割合利用", reading:"わりあいりよう", meaning:"ratio utilization", hint:"Using percentages", tags:["N3","soumatome"] }

];

window.kanjiData = kanjiData;