// ============================================================
//  options_data.js
//  These are the wrong-answer options the quiz picks from.
//  The more entries you add here, the more varied the wrong
//  options will be. They don't need to match kanji_data.js
//  exactly — just add all your readings and meanings here
//  so the quiz has a big pool to pick wrong answers from.
//
//  FORMAT — add one line per entry:
//  { reading:"よむ", meaning:"to read" },
// ============================================================

const optionsPool = [
  { reading:"にち", meaning:"sun / day"    },
  { reading:"つき", meaning:"moon / month" },
  { reading:"やま", meaning:"mountain"     },
  { reading:"かわ", meaning:"river"        },
  { reading:"ひ",   meaning:"fire"         },
  { reading:"みず", meaning:"water"        },
  { reading:"き",   meaning:"tree / wood"  },
  { reading:"ひと", meaning:"person"       },
  { reading:"くち", meaning:"mouth"        },
  { reading:"て",   meaning:"hand"         },

  { reading:"せいふ", meaning:"government" },
  { reading:"こっか", meaning:"nation / state" },
  { reading:"こくみん", meaning:"citizens" },
  { reading:"しみん", meaning:"citizen" },
  { reading:"じゅうみん", meaning:"resident" },
  { reading:"せんきょ", meaning:"election" },
  { reading:"せいじか", meaning:"politician" },
  { reading:"だいとうりょう", meaning:"president" },
  { reading:"しゅしょう", meaning:"prime minister" },
  { reading:"がいこう", meaning:"diplomacy" },

  { reading:"こくさいかんけい", meaning:"international relations" },
  { reading:"びょうどう", meaning:"equality" },
  { reading:"じゆう", meaning:"freedom" },
  { reading:"けんりょく", meaning:"power / authority" },
  { reading:"ぎむきょういく", meaning:"compulsory education" },
  { reading:"じんこうみつど", meaning:"population density" },
  { reading:"こうそうけんちく", meaning:"high-rise building" },
  { reading:"じゅうたくち", meaning:"residential area" },
  { reading:"しょうぎょうちく", meaning:"commercial district" },
  { reading:"こうぎょうちたい", meaning:"industrial zone" },

  { reading:"こうつうきかん", meaning:"transportation system" },
  { reading:"うんてんめんきょ", meaning:"driver license" },
  { reading:"ちゅうしゃきんし", meaning:"no parking" },
  { reading:"いっぽうつうこう", meaning:"one-way traffic" },
  { reading:"こうつうせいり", meaning:"traffic control" },
  { reading:"どうろこうじ", meaning:"road construction" },
  { reading:"えきまえひろば", meaning:"station plaza" },
  { reading:"こうそくれっしゃ", meaning:"high-speed train" },
  { reading:"じょうしゃじかん", meaning:"travel time" },
  { reading:"もくてきち", meaning:"destination" },

  { reading:"りょこうけいかく", meaning:"travel plan" },
  { reading:"かいがいりょこう", meaning:"overseas travel" },
  { reading:"こくないりょこう", meaning:"domestic travel" },
  { reading:"かんこうち", meaning:"tourist spot" },
  { reading:"しゅくはくりょうきん", meaning:"lodging fee" },
  { reading:"りょこうがいしゃ", meaning:"travel agency" },
  { reading:"りょこうあんない", meaning:"travel guide" },
  { reading:"かんこうめいしょ", meaning:"famous tourist place" },
  { reading:"おんせんりょかん", meaning:"hot spring inn" },
  { reading:"めいぶつりょうり", meaning:"local specialty dish" },

  { reading:"じもと", meaning:"local area" },
  { reading:"のうさんぶつ", meaning:"agricultural products" },
  { reading:"すいさんぶつ", meaning:"marine products" },
  { reading:"こうげいひん", meaning:"handicrafts" },
  { reading:"でんとうぶんか", meaning:"traditional culture" },
  { reading:"れきしてきたてもの", meaning:"historic building" },
  { reading:"ぶんかざい", meaning:"cultural property" },
  { reading:"せかいいさん", meaning:"World Heritage site" },
  { reading:"ゆうめいじん", meaning:"famous person" },
  { reading:"にんきしょうひん", meaning:"popular product" },

  { reading:"りゅうこうご", meaning:"buzzword" },
  { reading:"わかものぶんか", meaning:"youth culture" },
  { reading:"こうれいしゃ", meaning:"elderly person" },
  { reading:"しょうがいしゃ", meaning:"person with disability" },
  { reading:"いりょうきかん", meaning:"medical institution" },
  { reading:"けんこうしんだん", meaning:"health checkup" },
  { reading:"ちりょうほうほう", meaning:"treatment method" },
  { reading:"びょうきよぼう", meaning:"disease prevention" },
  { reading:"えいようぶそく", meaning:"lack of nutrition" },
  { reading:"せいしんじょうたい", meaning:"mental condition" },

  { reading:"きしゃ", meaning:"reporter" },
  { reading:"しんぶんしゃ", meaning:"newspaper company" },
  { reading:"ほうそうきょく", meaning:"broadcasting station" },
  { reading:"つうしん", meaning:"communication" },
  { reading:"じょうほう", meaning:"information" },
  { reading:"きじないよう", meaning:"article contents" },
  { reading:"しゅっぱん", meaning:"publishing" },
  { reading:"いんさつ", meaning:"printing" },
  { reading:"ざっししゃ", meaning:"magazine publisher" },
  { reading:"ちょしゃ", meaning:"author" },

  { reading:"どくしゃ", meaning:"reader" },
  { reading:"さくひんめい", meaning:"title of work" },
  { reading:"ほんやく", meaning:"translation" },
  { reading:"がいこくご", meaning:"foreign language" },
  { reading:"にほんごがく", meaning:"Japanese linguistics" },
  { reading:"かんじひょう", meaning:"kanji chart" },
  { reading:"はつおんきごう", meaning:"pronunciation symbol" },
  { reading:"いみないよう", meaning:"meaning/content" },
  { reading:"ことばづかい", meaning:"word usage" },
  { reading:"ひょうげんりょく", meaning:"expressive ability" },

  { reading:"たいけん", meaning:"personal experience" },
  { reading:"おもいで", meaning:"memory" },
  { reading:"ゆめ", meaning:"dream" },
  { reading:"きぼう", meaning:"hope" },
  { reading:"がんぼう", meaning:"desire / wish" },
  { reading:"もくひょう", meaning:"goal / target" },
  { reading:"せいこうしゃ", meaning:"successful person" },
  { reading:"しつぎょう", meaning:"unemployment" },
  { reading:"ひんこん", meaning:"poverty" },
  { reading:"とみ", meaning:"wealth" },

  { reading:"しさん", meaning:"assets" },
  { reading:"りえき", meaning:"profit" },
  { reading:"そんしつ", meaning:"loss" },
  { reading:"しょうひしゃ", meaning:"consumer" },
  { reading:"けいひ", meaning:"expenses" },
  { reading:"しゅうにゅう", meaning:"income" },
  { reading:"ししゅつ", meaning:"expenditure" },
  { reading:"ざいさん", meaning:"property / fortune" },
  { reading:"けいざいがく", meaning:"economics" },
  { reading:"とうし", meaning:"investment" },

  { reading:"きょういく", meaning:"education" },
  { reading:"きょうし", meaning:"teacher" },
  { reading:"せいと", meaning:"student / pupil" },
  { reading:"がっき", meaning:"school term" },
  { reading:"にゅうし", meaning:"entrance exam" },
  { reading:"せいせき", meaning:"grades / results" },
  { reading:"とうあん", meaning:"answer sheet" },
  { reading:"そつぎょうしき", meaning:"graduation ceremony" },
  { reading:"せんもん", meaning:"specialty" },
  { reading:"ちしき", meaning:"knowledge" },

  { reading:"きおく", meaning:"memory" },
  { reading:"そうぞう", meaning:"imagination" },
  { reading:"りかい", meaning:"understanding" },
  { reading:"はんだん", meaning:"judgment" },
  { reading:"せんたく", meaning:"selection / choice" },
  { reading:"けってい", meaning:"decision" },
  { reading:"どりょく", meaning:"effort" },
  { reading:"きょうりょく", meaning:"cooperation" },
  { reading:"きょうそう", meaning:"competition" },
  { reading:"かつどう", meaning:"activity" },

  { reading:"こうどう", meaning:"behavior / action" },
  { reading:"はっけん", meaning:"discovery" },
  { reading:"はつめい", meaning:"invention" },
  { reading:"けんきゅうしゃ", meaning:"researcher" },
  { reading:"じっけん", meaning:"experiment" },
  { reading:"ちょうさ", meaning:"investigation" },
  { reading:"ぶんせき", meaning:"analysis" },
  { reading:"とうけい", meaning:"statistics" },
  { reading:"けいさん", meaning:"calculation" },
  { reading:"すうじ", meaning:"number / numeral" },

  { reading:"たんい", meaning:"unit" },
  { reading:"りょう", meaning:"amount / quantity" },
  { reading:"ばい", meaning:"double / times" },
  { reading:"ぞうか", meaning:"increase" },
  { reading:"げんしょう", meaning:"decrease" },
  { reading:"へんか", meaning:"change" },
  { reading:"かいぜん", meaning:"improvement" },
  { reading:"かいりょう", meaning:"refinement" },
  { reading:"しんぽ", meaning:"progress" },
  { reading:"はったつ", meaning:"development" },

  { reading:"りゅうこう", meaning:"fashion / trend" },
  { reading:"けいゆ", meaning:"via / through" },
  { reading:"いどう", meaning:"movement" },
  { reading:"とうちゃくえき", meaning:"arrival station" },
  { reading:"じょうきゃく", meaning:"passenger" },
  { reading:"うんてんしゅ", meaning:"driver" },
  { reading:"こうくうけん", meaning:"airline ticket" },
  { reading:"でいりぐち", meaning:"entrance/exit" },
  { reading:"かいさつぐち", meaning:"ticket gate" },
  { reading:"まちあいしつ", meaning:"waiting room" },

  { reading:"じょうしゃけん", meaning:"train ticket" },
  { reading:"かたづけ", meaning:"tidying up" },
  { reading:"わすれもの", meaning:"lost item" },
  { reading:"おとしもの", meaning:"lost property" },
  { reading:"うけつけがかり", meaning:"reception clerk" },
  { reading:"あんないじょ", meaning:"information desk" },
  { reading:"はんばいてん", meaning:"retail store" },
  { reading:"しょうひんばんごう", meaning:"product number" },
  { reading:"はいそうりょう", meaning:"delivery fee" },
  { reading:"ざいこ", meaning:"inventory / stock" },

  { reading:"けいえいしゃ", meaning:"manager / executive" },
  { reading:"ろうどう", meaning:"labor / work" },
  { reading:"しょくぎょう", meaning:"occupation" },
  { reading:"きんむじかん", meaning:"working hours" },
  { reading:"きゅうけいしつ", meaning:"break room" },
  { reading:"めんどう", meaning:"trouble / bother" },
  { reading:"せきにんしゃ", meaning:"person in charge" },
  { reading:"じむしょ", meaning:"office" },
  { reading:"こうぎょう", meaning:"industry" },
  { reading:"きぎょう", meaning:"enterprise / corporation" },

  { reading:"けいひん", meaning:"prize" },
  { reading:"ねびき", meaning:"price reduction" },
  { reading:"げんば", meaning:"actual site" },
  { reading:"こういん", meaning:"factory worker" },
  { reading:"さぎょう", meaning:"task / operation" },
  { reading:"そうさ", meaning:"operation / control" },
  { reading:"ていし", meaning:"stop / halt" },
  { reading:"さいかい", meaning:"restart / reopen" },
  { reading:"へいてん", meaning:"shop closing" },
  { reading:"かいてん", meaning:"shop opening" },

  { reading:"まんせき", meaning:"full seats" },
  { reading:"くうせき", meaning:"vacant seat" },
  { reading:"よやくせき", meaning:"reserved seat" },
  { reading:"じゆうせき", meaning:"unreserved seat" },
  { reading:"きんえん", meaning:"no smoking" },
  { reading:"まんいん", meaning:"full capacity" },
  { reading:"こんざつ", meaning:"crowded" },
  { reading:"ぎょうれつ", meaning:"line / queue" },
  { reading:"じゅんばん", meaning:"turn / order" },
  { reading:"ばんごうふだ", meaning:"number ticket" },

  { reading:"さいふ", meaning:"wallet" },
  { reading:"げんきんばらい", meaning:"cash payment" },
  { reading:"ぎんこうこうざ", meaning:"bank account" },
  { reading:"あんき", meaning:"memorization" },
  { reading:"ふくしゅうもんだい", meaning:"review questions" },
  { reading:"かいとう", meaning:"answer / response" },
  { reading:"せいかい", meaning:"correct answer" },
  { reading:"ふせいかい", meaning:"incorrect answer" },
  { reading:"まんてん", meaning:"perfect score" },
  { reading:"てんすう", meaning:"score / points" },

  { reading:"ちり", meaning:"geography" },
  { reading:"すうがく", meaning:"mathematics" },
  { reading:"ぶつり", meaning:"physics" },
  { reading:"かがく", meaning:"chemistry" },
  { reading:"れきしがく", meaning:"historical studies" },
  { reading:"ぶんがく", meaning:"literature" },
  { reading:"げいじゅつ", meaning:"art" },
  { reading:"さくひんしゅう", meaning:"collection of works" },
  { reading:"てんらんかい", meaning:"exhibition" },
  { reading:"えいがさい", meaning:"film festival" },

  { reading:"さいじつ", meaning:"holiday" },
  { reading:"しゅくじつ", meaning:"public holiday" },
  { reading:"しんねんかい", meaning:"New Year party" },
  { reading:"せいじんしき", meaning:"coming-of-age ceremony" },
  { reading:"でんとう", meaning:"tradition" },
  { reading:"しゅうかん", meaning:"custom / habit" },
  { reading:"しゅうきょう", meaning:"religion" },
  { reading:"じんじゃ", meaning:"Shinto shrine" },
  { reading:"じいん", meaning:"Buddhist temple" },
  { reading:"かんきゃく", meaning:"audience / spectators" },

  { reading:"きぶん", meaning:"mood / feeling" },
  { reading:"きおん", meaning:"temperature" },
  { reading:"くうき", meaning:"air / atmosphere" },
  { reading:"てんこう", meaning:"weather condition" },
  { reading:"かいせい", meaning:"clear sky" },
  { reading:"おおあめ", meaning:"heavy rain" },
  { reading:"おおゆき", meaning:"heavy snow" },
  { reading:"きょうふう", meaning:"strong wind" },
  { reading:"しぜんかい", meaning:"natural world" },
  { reading:"せいぶつ", meaning:"living thing" },

  { reading:"しょくぶつ", meaning:"plant" },
  { reading:"どうぶつ", meaning:"animal" },
  { reading:"こんちゅう", meaning:"insect" },
  { reading:"ちょうるい", meaning:"birds" },
  { reading:"かいがん", meaning:"coast" },
  { reading:"みずうみ", meaning:"lake" },
  { reading:"すなはま", meaning:"sandy beach" },
  { reading:"いわ", meaning:"rock" },
  { reading:"しま", meaning:"island" },
  { reading:"はたけ", meaning:"field / farm" },

  { reading:"のうか", meaning:"farmer household" },
  { reading:"いちば", meaning:"market" },
  { reading:"しょうてん", meaning:"shop / store" },
  { reading:"ひゃっかてん", meaning:"department store" },
  { reading:"うりば", meaning:"sales floor" },
  { reading:"ねだん", meaning:"price" },
  { reading:"しょうひんけん", meaning:"gift certificate" },
  { reading:"りょうしゅうしょ", meaning:"receipt" },
  { reading:"よきん", meaning:"deposit savings" },
  { reading:"ぎんこういん", meaning:"bank employee" },

  { reading:"あんしょうばんごう", meaning:"PIN number" },
  { reading:"つうちょう", meaning:"bankbook" },
  { reading:"げんじゅうしょ", meaning:"current address" },
  { reading:"じゅうしょへんこう", meaning:"change of address" },
  { reading:"もうしこみしょ", meaning:"application form" },
  { reading:"きにゅうれい", meaning:"example entry" },
  { reading:"しょめい", meaning:"signature" },
  { reading:"しょうめいしょ", meaning:"certificate" },
  { reading:"みぶんしょうめいしょ", meaning:"identification card" },
  { reading:"りれきしょ", meaning:"resume / CV" },

  { reading:"こうつうじこ", meaning:"traffic accident" },
  { reading:"かさい", meaning:"fire disaster" },
  { reading:"ひなん", meaning:"evacuation" },
  { reading:"ひなんじょ", meaning:"evacuation shelter" },
  { reading:"きゅうじょ", meaning:"rescue" },
  { reading:"けいさつ", meaning:"police" },
  { reading:"しょうぼうしょ", meaning:"fire station" },
  { reading:"はんにん", meaning:"criminal" },
  { reading:"どろぼう", meaning:"thief" },
  { reading:"はんざい", meaning:"crime" },

  { reading:"ほうりつか", meaning:"legal expert" },
  { reading:"さいばん", meaning:"trial / judgment" },
  { reading:"べんごし", meaning:"lawyer" },
  { reading:"けんり", meaning:"rights" },
  { reading:"ぎむ", meaning:"duty / obligation" },
  { reading:"せきにん", meaning:"responsibility" },
  { reading:"ぜいきん", meaning:"tax" },
  { reading:"ほけん", meaning:"insurance" },
  { reading:"ねんきん", meaning:"pension" },
  { reading:"いりょうひ", meaning:"medical expenses" },



];
window.optionsPool = optionsPool;
